# Generated by Django 5.0.6 on 2024-05-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='defult@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
