# Generated by Django 5.0.6 on 2024-05-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userprofile_name_userprofile_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='friemd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
